// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7fYl8r2yfv22CfeHx19z3N67DRI1RA1M',
    appId: '1:808143356160:web:5e2efca7d812e160ed73e5',
    messagingSenderId: '808143356160',
    projectId: 'wander05',
    authDomain: 'wander05.firebaseapp.com',
    storageBucket: 'wander05.appspot.com',
    measurementId: 'G-33MQ5MFC62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRDb3YrQd6zY45CCsbJ6PyiitBuE-rB6w',
    appId: '1:808143356160:android:50d30b52b68ac68eed73e5',
    messagingSenderId: '808143356160',
    projectId: 'wander05',
    storageBucket: 'wander05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkTQFnR7lr3O3zhAr0hKyu5hvikcQAduY',
    appId: '1:808143356160:ios:c1d921aed175c021ed73e5',
    messagingSenderId: '808143356160',
    projectId: 'wander05',
    storageBucket: 'wander05.appspot.com',
    iosBundleId: 'com.example.wander05Final',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkTQFnR7lr3O3zhAr0hKyu5hvikcQAduY',
    appId: '1:808143356160:ios:e963d81b676255caed73e5',
    messagingSenderId: '808143356160',
    projectId: 'wander05',
    storageBucket: 'wander05.appspot.com',
    iosBundleId: 'com.example.wander05Final.RunnerTests',
  );
}
